apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: weather-app-pipeline
description: "Our finely crafted pipeline to deliver the weather-app to the world"
serialPipeline:
  stages:
  - targetId: taste
    profiles: [dev]
    strategy:
      standard:
        verify: true
  - targetId: serve
    profiles: [prod]
    strategy:
      standard:
        verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: taste
description: "The testing environment, where we taste the new brew"
run:
  location: projects/coffee-jitters/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: serve-us
description: "Our US production environment, serving up fresh weather data"
run:
  location: projects/coffee-jitters/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: serve-europe
description: "Our European production environment, for a continental brew"
run:
  location: projects/coffee-jitters/locations/europe-west1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: serve
description: "Our production environment, the final, perfect cup"
multiTarget:
  targetIds: [serve-us, serve-europe]
